apiVersion: apps/v1
kind: Deployment
metadata:
  name: must-gather-operator
  namespace: openshift-must-gather
spec:
  replicas: 1
  selector:
    matchLabels:
      name: must-gather-operator
  template:
    metadata:
      labels:
        name: must-gather-operator
    spec:
      serviceAccountName: must-gather-operator
      containers:
        - name: must-gather-operator
          # Replace this with the built image name
          image: quay.io/masayag/must-gather-operator:v0.0.1
          command:
          - must-gather-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "must-gather-operator"
